- name: install apache2
  apt:
    name: apache2
    state: latest

- name: start apache2
  service:
    name: apache2
    state: started

- name: populate service facts
  service_facts:

- name: assert apache2 is running
  assert:
    that: ansible_facts.services.apache2.state == "running"
